language: python
python:
  - "3.6"
before_install:
  - pip install --upgrade pip
  - pip install --upgrade pytest pytest-cov coveralls
install:
  - pip install -e .
script:
  - python -m pytest -v --cov epijinn --cov-report term-missing
after_success:
  - coveralls
