name: build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test pip installation
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          python -m pytest
